Repository CptWesley/GOALkeeper, pull requests merged in 2018-02, with the labels that each got.

#58 Non static parsers
  pom.xml
  src/main/java/nl/tudelft/goalkeeper/checking/violations/source/SourceParser.java
  src/main/java/nl/tudelft/goalkeeper/parser/Parser.java
  src/main/java/nl/tudelft/goalkeeper/parser/queries/ExpressionParser.java
  src/main/java/nl/tudelft/goalkeeper/parser/results/files/module/parsers/ActionParser.java
  src/main/java/nl/tudelft/goalkeeper/parser/results/files/module/parsers/ConditionParser.java
  src/main/java/nl/tudelft/goalkeeper/parser/results/files/module/parsers/MessageParser.java
  src/main/java/nl/tudelft/goalkeeper/parser/results/files/module/parsers/ModuleParser.java
  src/main/java/nl/tudelft/goalkeeper/parser/results/files/module/parsers/RuleParser.java
  src/test/java/nl/tudelft/goalkeeper/checking/violations/source/SourceParserTest.java
  src/test/java/nl/tudelft/goalkeeper/parser/ParserTest.java
  src/test/java/nl/tudelft/goalkeeper/parser/queries/ExpressionParserTest.java
  src/test/java/nl/tudelft/goalkeeper/parser/results/files/module/parsers/ActionParserTest.java
  src/test/java/nl/tudelft/goalkeeper/parser/results/files/module/parsers/ConditionParserTest.java
  src/test/java/nl/tudelft/goalkeeper/parser/results/files/module/parsers/MessageParserTest.java
  src/test/java/nl/tudelft/goalkeeper/parser/results/files/module/parsers/ModuleParserTest.java
  src/test/java/nl/tudelft/goalkeeper/parser/results/files/module/parsers/RuleParserTest.java
Labels: enhancement, review

#54 Actionspec parsing
  .travis.yml
  pom.xml
  src/main/java/nl/tudelft/goalkeeper/parser/Parser.java
  src/main/java/nl/tudelft/goalkeeper/parser/queries/PrologExpressionParser.java
  src/main/java/nl/tudelft/goalkeeper/parser/results/ParseResult.java
  src/main/java/nl/tudelft/goalkeeper/parser/results/files/actionspec/ActionSpecFile.java
  src/main/java/nl/tudelft/goalkeeper/parser/results/files/actionspec/ActionSpecification.java
  src/main/java/nl/tudelft/goalkeeper/parser/results/files/actionspec/parsers/ActionSpecParser.java
  src/main/java/nl/tudelft/goalkeeper/parser/results/files/actionspec/parsers/ActionSpecificationParser.java
  src/main/java/nl/tudelft/goalkeeper/parser/results/files/module/ModuleFile.java
  src/test/java/nl/tudelft/goalkeeper/parser/queries/ExpressionParserTest.java
  src/test/java/nl/tudelft/goalkeeper/parser/queries/PrologExpressionParserTest.java
  src/test/java/nl/tudelft/goalkeeper/parser/results/ParseResultTest.java
  src/test/java/nl/tudelft/goalkeeper/parser/results/files/actionspec/ActionSpecFileTest.java
  src/test/java/nl/tudelft/goalkeeper/parser/results/files/actionspec/ActionSpecificationTest.java
  src/test/java/nl/tudelft/goalkeeper/parser/results/files/actionspec/parsers/ActionSpecificationParserTest.java
  src/test/java/nl/tudelft/goalkeeper/parser/results/files/module/parsers/ActionParserTest.java
  src/test/java/nl/tudelft/goalkeeper/parser/results/files/module/parsers/ConditionParserTest.java
  src/test/java/nl/tudelft/goalkeeper/parser/results/files/module/parsers/RuleParserTest.java
Labels: enhancement, feature, review

#60 Fix goalupdate
  src/main/java/nl/tudelft/goalkeeper/parser/Parser.java
  src/test/java/nl/tudelft/goalkeeper/parser/ParserTest.java
Labels: review
